import {db,saveDB,uid,esc,money} from "./storage.js"; import {openModal,closeModal,appSelect,toast,tradeCard,setupImageInput} from "./ui.js";
export function openTrade(id=""){
 const t=db.trades.find(x=>x.id===id)||{id:"",date:new Date().toISOString().slice(0,10),symbol:"",direction:"Long",setup:"",timeframe:"",entry:"",exit:"",sl:"",target:"",qty:"",pnl:"",r:"",risk:"",riskPct:"",rr:"",rule:true,emotion:"",mistake:"",entryReason:"",exitReason:"",notes:"",screenshots:[]};
 openModal(`<div class="modal-head"><h2>${id?"Trade Detail / Edit":"New Trade"}</h2><button class="x" onclick="closeModal()">×</button></div>
 <form class="form" onsubmit="submitTrade(event,'${id}')">
 <div class="formgrid">
 <div class="field"><label>Date</label><input class="input" type="date" id="t_date" value="${esc(t.date)}" required></div><div class="field"><label>Symbol</label><input class="input" id="t_symbol" value="${esc(t.symbol)}" placeholder="NIFTY / RELIANCE" required></div>
 <div class="field"><label>Direction</label>${appSelect("t_direction",t.direction,[["Long","Long"],["Short","Short"]])}</div><div class="field"><label>Setup</label><input class="input" id="t_setup" value="${esc(t.setup)}" placeholder="Your setup"></div>
 <div class="field"><label>Timeframe</label><input class="input" id="t_tf" value="${esc(t.timeframe)}" placeholder="5m / 15m / 1H"></div><div class="field"><label>Quantity</label><input class="input" type="number" step="any" id="t_qty" value="${esc(t.qty)}"></div>
 <div class="field"><label>Entry</label><input class="input" type="number" step="any" id="t_entry" value="${esc(t.entry)}"></div><div class="field"><label>Exit</label><input class="input" type="number" step="any" id="t_exit" value="${esc(t.exit)}"></div>
 <div class="field"><label>Stop Loss</label><input class="input" type="number" step="any" id="t_sl" value="${esc(t.sl)}"></div><div class="field"><label>Target</label><input class="input" type="number" step="any" id="t_target" value="${esc(t.target)}"></div>
 <div class="field"><label>Net P&L ₹</label><input class="input" type="number" step="any" id="t_pnl" value="${esc(t.pnl)}" placeholder="After charges"></div><div class="field"><label>Result R</label><input class="input" type="number" step="any" id="t_r" value="${esc(t.r)}"></div>
 </div>
 <div class="result-grid"><div class="mini"><span>Risk ₹</span><b id="tradeRiskPreview">—</b></div><div class="mini"><span>Risk %</span><b id="tradeRiskPctPreview">—</b></div><div class="mini"><span>Planned R:R</span><b id="tradeRRPreview">—</b></div></div>
 <div class="field"><label>Rule adherence</label>${appSelect("t_rule",String(!!t.rule),[["true","Followed rules"],["false","Rule violation"]])}</div>
 <div class="formgrid"><div class="field"><label>Emotion before trade</label><input class="input" id="t_emotion" value="${esc(t.emotion)}" placeholder="Calm / FOMO / revenge"></div><div class="field"><label>Mistake / violation</label><input class="input" id="t_mistake" value="${esc(t.mistake)}"></div></div>
 <div class="formgrid"><div class="field"><label>Entry reason</label><textarea class="textarea" id="t_entryReason">${esc(t.entryReason)}</textarea></div><div class="field"><label>Exit reason</label><textarea class="textarea" id="t_exitReason">${esc(t.exitReason)}</textarea></div></div>
 <div class="field"><label>Notes</label><textarea class="textarea" id="t_notes">${esc(t.notes)}</textarea></div>
 ${setupImageInput("t_images","Chart Screenshots (camera/gallery)")}
 <div id="existingPhotos">${t.screenshots?.length?`<div class="photo-grid">${t.screenshots.map(s=>`<img src="${s}" alt="Trade chart">`).join("")}</div>`:""}</div>
 <div class="form-actions"><button type="button" class="btn" onclick="closeModal()">Cancel</button>${id?`<button type="button" class="btn danger" onclick="deleteTrade('${id}')">Delete</button>`:""}<button class="btn primary">${id?"Save Changes":"Save Trade"}</button></div></form>`);
 ["t_entry","t_exit","t_sl","t_target","t_qty"].forEach(x=>document.getElementById(x)?.addEventListener("input",previewTrade));
 previewTrade();
}
function previewTrade(){const e=+t_entry.value||0,sl=+t_sl.value||0,tar=+t_target.value||0,qty=+t_qty.value||0,dir=t_direction.value;const riskUnit=Math.abs(e-sl),rewardUnit=Math.abs(tar-e);document.getElementById("tradeRiskPreview").textContent=riskUnit&&qty?"₹"+money(riskUnit*qty):"—";document.getElementById("tradeRiskPctPreview").textContent="—";document.getElementById("tradeRRPreview").textContent=riskUnit?((rewardUnit/riskUnit).toFixed(2)+":1"):"—"}
async function fileToDataURL(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
export async function submitTrade(e,id){e.preventDefault();const old=db.trades.find(x=>x.id===id);let screenshots=old?.screenshots||[];const files=[...document.getElementById("t_images").files];if(files.length){const data=await Promise.all(files.slice(0,4).map(fileToDataURL));screenshots=[...screenshots,...data]}const t={id:id||uid(),date:t_date.value,symbol:t_symbol.value.trim().toUpperCase(),direction:t_direction.value,setup:t_setup.value.trim()||"Unspecified",timeframe:t_tf.value.trim(),entry:+t_entry.value||0,exit:+t_exit.value||0,sl:+t_sl.value||0,target:+t_target.value||0,qty:+t_qty.value||0,pnl:+t_pnl.value||0,r:+t_r.value||0,rule:t_rule.value==="true",emotion:t_emotion.value.trim(),mistake:t_mistake.value.trim(),entryReason:t_entryReason.value.trim(),exitReason:t_exitReason.value.trim(),notes:t_notes.value.trim(),screenshots,created:old?.created||Date.now()};const risk=Math.abs(t.entry-t.sl)*t.qty;t.risk=risk;t.riskPct=0;t.rr=Math.abs(t.entry-t.sl)?Math.abs(t.target-t.entry)/Math.abs(t.entry-t.sl):0;if(old)Object.assign(old,t);else db.trades.unshift(t);saveDB();closeModal();toast(old?"Trade updated":"Trade added")}
export function deleteTrade(id){if(!confirm("Delete this trade permanently?"))return;db.trades=db.trades.filter(x=>x.id!==id);saveDB();toast("Trade deleted");if(document.getElementById("modal").classList.contains("open"))closeModal()}
export function renderTrades(){const q=(document.getElementById("search")?.value||"").toLowerCase(),d=document.getElementById("filterDir")?.value||"",r=document.getElementById("filterResult")?.value||"";let a=db.trades.filter(t=>(!q||[t.symbol,t.setup,t.notes,t.mistake,t.emotion].join(" ").toLowerCase().includes(q))&&(!d||t.direction===d)&&(!r||(r==="win"?t.r>0:r==="loss"?t.r<0:t.r===0)));const el=document.getElementById("tradesList");el.innerHTML=a.length?`<div class="trade-list">${a.map(tradeCard).join("")}</div>`:`<div class="empty"><div><b>No trades found</b><span>Add your first trade to start building data.</span></div></div>`}
window.openTrade=openTrade;window.deleteTrade=deleteTrade;
